[project]
name = "gds-hierarchical-demo"
version = "0.1.0"
description = "A demonstration for generating hierarchical GDSII files with nested patterns using gdstk library"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
